### ISSUE TITLE
The server won't start when a webhookURL is passed to the start() function

### ISSUE THREAD

**Issue by martenls** [twitterdev/autohook#15]
When `webhook.start(customURL)` is called the server won't start.

### Expected behavior

When `webhook.start(customURL)` is called the server should be started with the `startServer()` function.

### Actual behavior

The `startServer()` function is only executed when no url is passed to `webhook.start()`

### Steps to reproduce the behavior

Call `webhook.start()` with a custom URL.

**Comment by iamdaniele** [comment]
@martenls this is intended since [v1.3.0](https://github.com/twitterdev/autohook/releases/tag/v1.3.0). We made a change to make `setWebhook()` private, and to explicitly requiring to call `startserver()` if you have a custom URL. This is to enable a more sophisticated server configuration, especially in cases where the HTTP router is configured as a different microservice.

To better understand how to start the server when you also need to specify a custom URL, refer to our [standalone server example](https://github.com/twitterdev/autohook/blob/v1.3.0/test/standalone-server.js).
